# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 10:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2016, 1, 24, 10, 16, 30, 153698, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
