# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 10:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default=datetime.datetime(2016, 1, 24, 10, 53, 48, 276533, tzinfo=utc), max_length=255, verbose_name='\u0418\u043c\u044f'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default=datetime.datetime(2016, 1, 24, 10, 54, 3, 692155, tzinfo=utc), max_length=255, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f'),
            preserve_default=False,
        ),
    ]
