# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20160125_2007'),
        ('profiles', '0005_profile_favorites'),
    ]

    operations = [
    ]
