# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_auto_20160116_0647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': '\u0437\u0430\u0432\u0435\u0434\u0435\u043d\u0438\u0435', 'verbose_name_plural': '\u0437\u0430\u0432\u0435\u0434\u0435\u043d\u0438\u044f'},
        ),
        migrations.AddField(
            model_name='place',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='\u041e\u043f\u0443\u0431\u043b\u0438\u043a\u043e\u0432\u0430\u043d\u043e'),
        ),
    ]
