# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 13:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0007_auto_20160120_2035'),
        ('place', '0007_auto_20160120_2020'),
    ]

    operations = [
    ]
