# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0008_merge'),
        ('place', '0007_auto_20160120_2018'),
    ]

    operations = [
    ]
