# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0009_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placepicture',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='place.Place'),
        ),
    ]
