# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 07:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0010_auto_20160125_2007'),
        ('place', '0010_auto_20160125_2006'),
    ]

    operations = [
    ]
