# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0011_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_name', models.CharField(max_length=100)),
                ('position', geoposition.fields.GeopositionField(max_length=42)),
            ],
        ),
    ]
