# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0012_detailmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
    ]
