# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 13:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0013_auto_20160127_1922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detailmap',
            options={'verbose_name': '\u043a\u0430\u0440\u0442\u0430', 'verbose_name_plural': '\u043a\u0430\u0440\u0442\u044b'},
        ),
    ]
